name: nawax_radio
description: "Nawax Radio 24/7 Persian Music Streaming App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🎧 Audio streaming
  just_audio: ^0.9.36
  just_audio_platform_interface: ^4.3.0

  # 🌐 HTTP requests
  http: ^1.2.0

  # ✨ Animations
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # 👈 اینو اضافه کن

flutter:
  uses-material-design: true

  assets:
    - assets/icons/nawax.png   # 👈 اینو اضافه کن


# 👇 این بخش جدید رو کامل پایین فایل بذار
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/nawax.png"
  remove_alpha_ios: true
